
   
[package]
name = "nucliadb_node_binding"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "nucliadb_node_binding"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.15.1", features = ["extension-module"] }
pyo3-asyncio = {version = "0.16.0", features = ["tokio-runtime"] }
nucliadb_node = { path = "../../nucliadb_node" }
nucliadb_protos = { path = "../../nucliadb_protos/rust" }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
log = "0.4"
bincode = "1.3.3"
prost = "0.9"
prost-types = "0.9"
# # serde_json is just for the example, not required in general
# serde_json = "1.0"
# uuid = "0.8.2"
# thiserror = "1.0.30"
# tonic = "0.6.2"

[dev-dependencies]
env_logger = "0.8.4"