[package]
name = "nucliadb_cluster_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "nucliadb_cluster_rust"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.16.5", features = ["extension-module"] }
nucliadb-cluster = { path = "../../nucliadb_cluster" }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
log = "0.4"
anyhow = "1.0"

# serde_json is just for the example, not required in general
serde_json = "1.0"
uuid = "0.8.2"
thiserror = "1.0.30"
tonic = "0.7"

[dev-dependencies]
env_logger = "0.8.4"