[package]
name = "nucliadb-cluster"
version = "0.1.0"
authors = ['Bosutech S.L.']
edition = "2018"
license = "AGPL-3.0-or-later"
description = "nucliadb cluster membership"
repository = "https://github.com/stashify/nucliadb"
homepage = "https://nuclia.com/"
documentation = "https://nuclia.com/"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
flume = "0.10"
nucliadb-swim = { version = "0.1", path = "../nucliadb_swim" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1.7", features = [ "full" ] }
tokio-stream = { version = "0.1.6", features = [ "sync" ] }
tonic = "0.5.2"
tracing = "0.1"
uuid = "0.8"
log = "0.4.14"
env_logger = "0.9.0"

[dev-dependencies]
itertools = '0.10'
tempfile = "3"
