[workspace]
resolver = "1"

members = [
  "nucliadb_core",
  "nucliadb_node",
  "nucliadb_node_binding",
  "nucliadb_paragraphs",
  "nucliadb_protos/rust",
  "nucliadb_relations",
  "nucliadb_telemetry",
  "nucliadb_texts",
  "nucliadb_vectors",
  "vectors_benchmark",
]
