apiVersion: v1
kind: ConfigMap
metadata:
  name: train-config
  labels:
    app: train
    app.kubernetes.io/name: train
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    version: "{{ .Chart.Version | replace "+" "_" }}"
    chart: "{{ .Chart.Name }}"
data:
  GRPC_PORT: {{ .Values.serving.grpc_port | quote }}
  SENTRY_URL: {{ .Values.running.sentry_url }}
  SERVING_PORT: {{ .Values.serving.port | quote }}
  JAEGER_ENABLED: {{ .Values.tracing.enabled | quote }}
  METRICS_PORT: {{ .Values.serving.metricsPort | quote }}

