apiVersion: v1
description: nucliadb Ingest Chart
name: nucliadb_ingest
version: 99999.99999.99999
appVersion: 99999.99999.99999
keywords:
  - nucliadb
  - nuclia
home: https://nuclia.com
icon: https://nuclia.com/logo.png
sources:
  - https://github.com/nuclia/nucliadb
maintainers:
  - name: Nuclia
    email: nucliadb@nuclia.com
