apiVersion: v1
kind: Service
metadata:
  name: node
  labels:
    app: node
    app.kubernetes.io/name: node
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    version: "{{ .Chart.Version | replace "+" "_" }}"
    chart: "{{ .Chart.Name }}"
spec:
  selector:
    app: node
    chart: "{{ .Chart.Name }}"
  clusterIP: None
  ports:
  - name: grpc-reader
    port: {{ .Values.serving.grpc_reader }}
    protocol: TCP
    appProtocol: grpc
  - name: grpc-writer
    port: {{ .Values.serving.grpc_writer }}
    protocol: TCP
    appProtocol: grpc
  - name: grpc-sidecar
    port: {{ .Values.serving.grpc_sidecar }}
    protocol: TCP
    appProtocol: grpc
