apiVersion: v1
kind: Service
metadata:
  name: node-0-fixed-ip
  labels:
    app: node
    app.kubernetes.io/name: node
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    version: "{{ .Chart.Version | replace "+" "_" }}"
    chart: "{{ .Chart.Name }}"
spec:
  selector:
    app: node
    chart: "{{ .Chart.Name }}"
    statefulset.kubernetes.io/pod-name: node-0
  clusterIP: {{ .Values.serving.node0_svc_fixed_ip }}
  ports:
  - name: grpc-reader
    port: {{ .Values.serving.grpc_reader }}
    protocol: TCP
    appProtocol: grpc
  - name: grpc-writer
    port: {{ .Values.serving.grpc_writer }}
    protocol: TCP
    appProtocol: grpc