global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: "tidb-cluster"
    scrape_interval: 5s
    honor_labels: true
    static_configs:
      - targets: ["pushgateway:9091"]
        labels:
          cluster: "tidb-cluster"
rule_files:
  - "pd.rules.yml"
  - "tikv.rules.yml"
