apiVersion: v1
kind: Service
metadata:
  name: ingest-headless
  labels:
    app: ingest
    app.kubernetes.io/name: ingest
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    version: "{{ .Chart.Version | replace "+" "_" }}"
    chart: "{{ .Chart.Name }}"
spec:
  selector:
    app: ingest
    chart: "{{ .Chart.Name }}"
  clusterIP: None
  ports:
    - name: grpc-ingest
      port: {{ .Values.serving.grpc }}
      protocol: TCP
      appProtocol: grpc
    - name: metrics
      port: {{ .Values.serving.metricsPort}}
      protocol: TCP
      appProtocol: http