[package]
name = "nucliadb_protos"
version = "0.0.1"
keywords = ["proto3", "rust", "protoc"]
edition = "2021"
build = "build.rs"
authors = ["nucliadb <nucliadb@nuclia.com>"]
license = 'AGPL-3.0-or-later'
description = "Node of nucliadb"
repository = "https://github.com/nuclia/nucliadb"
homepage = "https://nuclia.com/"
documentation = "https://nuclia.com"

[build-dependencies]
tonic-build = "0.6"
prost-build = "0.9"
prost-wkt-build = "0.3"

[dependencies]
tonic = "0.6"
prost-types = "0.9"
prost-wkt = "0.3"
prost-wkt-types = "0.3"
prost = { version = "0.10", default-features = false, features = ["prost-derive"] }
serde = { version = "1.0", features = ["derive"] }
