[package]
name = "nidx_tantivy"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0-or-later"

[dependencies]
anyhow = "1.0.91"
nidx_types = { version = "0.1.0", path = "../nidx_types" }
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
tantivy = "0.24.1"
tantivy-common = "0.9.0"
tempfile = "3.13.0"
