[package]
name = "nidx_relation"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0-or-later"

[dependencies]
anyhow = "1.0.92"
deunicode = "1.3.2"
nidx_protos = { version = "0.1.0", path = "../nidx_protos" }
nidx_tantivy = { version = "0.1.0", path = "../nidx_tantivy" }
nidx_types = { version = "0.1.0", path = "../nidx_types" }
serde = { version = "1.0.219", features = ["derive"] }
tantivy = "0.24"
tracing = "0.1.41"
uuid = "1.16.0"

[dev-dependencies]
tempfile = "3"
lazy_static = "1.4.0"
nidx_tests = { path = "../nidx_tests" }
