apiVersion: v1
description: nucliadb Chart
name: nucliadb_search
version: 99999.99999.99999
appVersion: 99999.99999.99999
keywords:
  - nucliadb
  - nuclia
home: https://nuclia.com
icon: https://nuclia.com/wp-content/uploads/2021/12/logo-fooer.png
sources:
  - https://github.com/nuclia/nucliadb
maintainers:
  - name: Nuclia
    email: nucliadb@nuclia.com
