name: nucliadb Client (py)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  # Job to run pre-checks
  pre-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3.1.0
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install package
        run: |
          pip install -r code-requirements.txt
      - name: Run pre-checks
        run: |
          flake8 nucliadb_client --config=nucliadb_client/setup.cfg
          isort -c --profile black nucliadb_client/
          black --check --verbose nucliadb_client

  # Job to run tests
  tests:
    name: NucliaDBClientTests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3.1.0
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install the package
        run: |
          pip install --upgrade pip
          pip install -r test-requirements.txt
          pip install -r nucliadb_client/requirements-test.txt
          pip install -r nucliadb_client/requirements-source.txt
          pip install -r nucliadb_client/requirements.txt
          pip install -e nucliadb_client

      - name: Check mypy
        run: |
          MYPYPATH=./mypy_stubs mypy nucliadb_client/

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            nucliadb_node_modified:
              - 'nucliadb_node/**'
            nucliadb_modified:
              - 'nucliadb/**'

      - name: Build Nucliadb docker image (with compiled node bindings) for testing
        if: steps.filter.outputs.nucliadb_node_modified == 'true'
        run: |
          docker build -t nuclia/nucliadb:latest -f Dockerfile.withbinding --build-arg RUST_BUILD_PROFILE=dev .

      - name: Build Nucliadb docker image (without bindings) for testing
        if: ${{ steps.filter.outputs.nucliadb_node_modified != 'true' && steps.filter.outputs.nucliadb_modified == 'true' }}
        run: |
          docker build -t nuclia/nucliadb:latest -f Dockerfile .

      - name: Run tests
        run: |
          pytest -rfE --cov=nucliadb_client -s --tb=native -v --cov-report xml --cov-append nucliadb_client/nucliadb_client

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          flags: client
