name: Release NucliaDB Client

on:
  push:
    branches:
      - main
    paths:
      - "nucliadb_client/VERSION"

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-2016"]
    env:
      CIBW_ARCHS_LINUX: auto aarch64
      CIBW_ARCHS_MACOS: x86_64 universal2 arm64
      # Building for one python version is enough, since this is a
      # ctypes-based 'universal binary wheel' (py3-none-*) not
      # linked to a specific python version or implementation.
      CIBW_BUILD: "cp39-*"

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up msbuild (Windows-only)
        uses: microsoft/setup-msbuild@v1.0.2
        if: startsWith(matrix.os, 'windows')

      - uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Build wheels
        run: pipx run cibuildwheel --output-dir dist nucliadb_client

      - name: Publish distribution ðŸ“¦ to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
