[package]
name = "nidx_protos"
version = "0.1.0"
edition = "2024"
build = "build.rs"
license = "AGPL-3.0-or-later"

[build-dependencies]
tonic-build = "0.12.3"

[dependencies]
tonic = "0.12.3"
prost = "0.13"
prost-types = "0.13"
