[package]
name = "nidx_protos"
version = "0.1.0"
edition = "2024"
build = "build.rs"
license = "AGPL-3.0-or-later"

[build-dependencies]
tonic-build = "0.14.2"
tonic-prost-build = "0.14.2"

[dependencies]
tonic = "0.14.2"
prost = "0.14"
prost-types = "0.14"
tonic-prost = "0.14.2"
